### ISSUE TITLE
Use integer for vlan_id

### ISSUE THREAD

**Issue by bartv** [inmanta/net#5]
The compiler now supports integer types. Currently 3.14 is also a valid vlan.

**Comment by andraskvr** [comment]
It's already supposed to be a (constrained) integer:
https://github.com/inmanta/net/blob/6d581cee462371409215b93f326c264a05aadca6/model/_init.cf#L27
@bartv Is this ticket still necessary?

**Comment by bartv** [comment]
No, seems I made a mistake when I created this ticket.
